
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    assignees:
      - "armand0w"

  - package-ecosystem: "docker"
    directory: "/images/java/17/headless"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Mexico_City"
    target-branch: "main"
    assignees:
      - "armand0w"

  - package-ecosystem: "docker"
    directory: "/images/java/21/headless"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Mexico_City"
    target-branch: "main"
    assignees:
      - "armand0w"