name: Java 17 Headless

permissions: write-all

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dependabot/*
    paths:
      - 'images/java/17/headless/Dockerfile'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: armand0w/java
          tags: |
            type=raw,value=openjdk-17-jre-headless
          flavor: |
            latest=false
            prefix=
            suffix=

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: armand0w
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: images/java/17/headless
          platforms: linux/386,linux/arm/v6,linux/arm/v7,linux/arm/v8,linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Merge PR
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GH }}
